<?php
/**
 * @class HooshMarketing_Marketo_Block_Template
 * @var $this HooshMarketing_Marketo_Block_Template
 */
?>
<?php
    $_fields = $this->getIncorrectCredentialFields();
?>
<?php if($_fields): ?>
    <div class="notification-global notification-global-notice">
        <?php echo $this->helper('hoosh_marketo')->__('Next marketo api credentials are missing: %s <a href="%s">configuration</a>.',
                $_fields, $this->_getHelper()->getSystemConfigUrl()
            )?>
    </div>
<?php endif; ?>